### ISSUE TITLE
consider adding ffmpeg-static

### ISSUE THREAD

**Issue by derhuerst** [transitive-bullshit/awesome-ffmpeg#1]
[`ffmpeg-static`](https://github.com/eugeneware/ffmpeg-static) let's you use ffmpeg in your tools without depending on a global installation of it. It works like the [`node` package](https://www.npmjs.com/package/node).

**Comment by transitive-bullshit** [comment]
Thanks @derhuerst! I didn't know about `ffmpeg-static` previously and will definitely be using it in the future.  Added it to the list!

Previously, I've always just [installed](https://github.com/transitive-bullshit/ffmpeg-extract-frames/blob/master/.travis.yml) ffmpeg on CI builds.

Any thoughts on how to only install `ffmpeg-static` only if there isn't already a build of ffmpeg available? I'm thinking that `ffmpeg-static` is great for CI builds, but I don't want to force a specific version of ffmpeg on users for normal `npm install` usage as it's both a large dependency and also kind of restrictive if you need to use a custom ffmpeg for other types of stuff (like I do [here](https://github.com/transitive-bullshit/ffmpeg-gl-transition)).

**Comment by derhuerst** [comment]
Maybe something like this in bash?

```bash
ffmpeg -v || npm i ffmpeg-static --no-save
```
